# Generated by Django 5.2.9 on 2025-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalparty',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='party_logos/'),
        ),
    ]
