# Generated by Django 5.2.9 on 2026-04-30 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_remove_politicalparty_logo_url_politicalparty_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_ward_results', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_results', to='election.politicalparty')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_results', to='election.ward')),
            ],
            options={
                'ordering': ['ward', 'party'],
                'indexes': [models.Index(fields=['ward', 'party'], name='election_wa_ward_id_ab5da4_idx'), models.Index(fields=['ward'], name='election_wa_ward_id_0fd8fb_idx')],
                'unique_together': {('ward', 'party')},
            },
        ),
    ]
