# Generated by Django 5.2.9 on 2026-07-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_electionresult_dataset_localgovernmentarea_dataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApcElectionResult',
            fields=[
            ],
            options={
                'verbose_name': 'Election Result (APC)',
                'verbose_name_plural': 'Election Results (APC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('election.electionresult',),
        ),
        migrations.CreateModel(
            name='ApcLocalGovernmentArea',
            fields=[
            ],
            options={
                'verbose_name': 'Local Government Area (APC)',
                'verbose_name_plural': 'Local Government Areas (APC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('election.localgovernmentarea',),
        ),
        migrations.CreateModel(
            name='ApcPollingUnit',
            fields=[
            ],
            options={
                'verbose_name': 'Polling Unit (APC)',
                'verbose_name_plural': 'Polling Units (APC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('election.pollingunit',),
        ),
        migrations.CreateModel(
            name='ApcWard',
            fields=[
            ],
            options={
                'verbose_name': 'Ward (APC)',
                'verbose_name_plural': 'Wards (APC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('election.ward',),
        ),
        migrations.CreateModel(
            name='ApcWardResult',
            fields=[
            ],
            options={
                'verbose_name': 'Ward Result (APC)',
                'verbose_name_plural': 'Ward Results (APC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('election.wardresult',),
        ),
    ]
