# Generated by Django 5.2.9 on 2026-07-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_apcelectionresult_apclocalgovernmentarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_lgas',
            field=models.ManyToManyField(blank=True, help_text='LGAs this clerk may access. Admins can access every LGA regardless.', related_name='assigned_clerks', to='election.localgovernmentarea'),
        ),
    ]
