import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from election.models import LocalGovernmentArea, Ward, PollingUnit

lga = LocalGovernmentArea.objects.get(name='WUKARI')

data = {
    'AKWANA': [
        'AKWANA PRI. SCH. AGHANEN',
        'AKWANA, AKWANA PRIMARY SCHOOL',
        'ANDU KATSWEN, ANDU KATSWEN PRIMARY SCHOOL',
        'ARUFU, ARUFU PRIMARY SCHOOL',
        'DAPYE PRI. SCH. BEGHAYAM',
        'FYAYI, FYAYI PRIMARY SCHOOL',
        'GIDAN IKWE PRI. SCH.',
        'IKWE, IKWE PRIMARY SCHOOL',
        'L.G. DISPENSARY KOFAR MASALLACHI',
        'ARUFU PRI. SCH. KOFAR SANGARI',
        'L.G. DISPENSARY, FYAYI',
        'NEAR KOFAR KUNYI',
        'KWATAN TSUFA, TSWADIGE',
        'TSWADIGE, TSOKWA KASSU',
        'TSOKWA KASSU PRI. SCH.',
        'TOR SAAI PRI. SCH.',
        'L.G. DISPENSARY AKWANA',
    ],
    'AVYI': [
        'AUDU KOMBE, AUDU KOMBE',
        'IDOFI PRI. SCH.',
        'NEAR KOFAR ADI',
        'NEAR KOFAR BURA',
        'ST. MARY PRI. SCH.',
        'NEAR KOFAR TSOJON IKWE',
        'NEAR KOFAR LIMAN SULE',
        'LOW COST, LOW COST',
        'NEAR KOFAR MAI UNGUWA USENI LIKITA',
        'MAL. BELLO N/PRIMARY SCHOOL',
        'PRISON SERVICE, PRISON SERVICE',
        'PWADZU, PWADZU PRIMARY SCHOOL',
        "ST. MARY'S PRIMARY SCHOOL",
    ],
    'BANTAJE': [
        'ATORO PRI. SCH.',
        'ATSAGA PRI. SCH.',
        'BANTAJE PRIMARY SCHOOL I',
        'BANTAJE PRIMARY SCHOOL II',
        'CHEDIYA, CHEDIYA PRIMARY SCHOOL',
        'CHIYE/DOKO PRI. SCH.',
        'TUNARI PRI. SCH. DENIS KUKU',
        'NEAR KOFAR GALADIMA NYANKWALA',
        'GBORBEGA PRI. SCH.',
        'NEAR KOFAR GONDO',
        'GINDIN DOROWA I, GINDIN DOROWA PRIMARY SCHOOL',
        'GINDIN DOROWA II, GINDIN DOROWA PRIMARY SCHOOL',
        'KAMBARI, KAMBARI PRIMARY SCHOOL',
        'NEAR KOFAR SARKIN BANTAJE',
        'L.G. DISPENSARY G. DOROWA',
        'TUNARI PRI. SCH. KOFAR SARKIN NOMA',
        'NEAR KOFAR TOMA, TUNARI',
        'PRI. SCH. KWATAN DOYA',
        'MAHANGA PRI. SCH. KOFAR JAHUN',
        'NEAR KOFAR KACHALLA',
        'LOCAL GOVT. DISPENSARY',
        'MAHANGA PRI. SCH.',
        'MALE PRI. SCH.',
        'NAKAMBO PRI. SCH.',
        'NATIRDE PRI. SCH.',
        'NYANKWALA, NYANKWALA PRIMARY SCHOOL',
        'NWONKO, NWONKO PRIMARY SCHOOL',
        'NYANHINA PRI. SCH.',
        'SAKYO, SAKYO PRIMARY SCHOOL',
        'TUNARI, TUNARI PRIMARY SCHOOL',
        'G.D.S.S. CHEDIYA',
    ],
    'CHONKU': [
        'NEAR AKA AKAH, JANDEKYULA',
        'BYE-GYA PRI. SCH.',
        'CHUDAN, CHUDAN PRIMARY SCHOOL',
        'CHONKU, CHONKU PRIMARY SCHOOL',
        'DAPYE, DAPYE',
        'GBORCHA PRI. SCH.',
        'ANDO IGBA PRI. SCH.',
        'JABWAJE PRI. SCH.',
        'KYAYOR PRI. SCH.',
        'KUMUTU, KUMUTU PRIMARY SCHOOL',
        'NUMA, NUMA PRIMARY SCHOOL',
        'NWUTSA, NWUTSA PRIMARY SCHOOL',
        'NWUKAN PRI. SCH.',
        'NWOBAN, NWOBAN PRIMARY SCHOOL',
        'RITI, RITI PRIMARY SCHOOL',
        'TOR IORYINA, TOR IORYINA',
        'L.G. DISPENSARY, RITI',
    ],
    'HOSPITAL': [
        'NEAR B.B. BREAD',
        'EBENEZER PRIMARY SCHOOL',
        'NEAR HALIRU DOGARA',
        'NEAR KOFAR ATO UMARU',
        'NEAR KOFAR MAMMAN KATOR I',
        'NEAR KOFAR BALA BELLO',
        'NEAR KOFAR YAMUSA',
        'NURUL ISLAM PRI. SCH. KOFAR SALE VYONKU',
        'G.J.S.S. WUKARI',
        'NEAR KOFAR ABDUL W. SARKIN PAWA',
        'NURUL ISLAM PRI. SCH. KOFAR GARBAN LOKO',
        'NEAR KOFAR DANLADI M. YUSUF',
        'NURUL ISLAM PRI. SCH. KOFAR NWUNGYE',
        'M. G.G.S.S.',
        'NURUL ISLAM, N.I. PRIMARY SCHOOL',
        'EBENEZER PRI. SCH. UMARU KANKANI',
        'STATE POLY, STATE POLYTECHNIC',
    ],
    'JIBU': [
        'ALAMINI, ALAMINI PRIMARY SCHOOL',
        'MDG HOSPITAL BAKA GARI',
        'BENKAHO PRI. SCH.',
        'BYE-PYI, BYE-PYI PRIMARY SCHOOL',
        'BYE-YORA PRI. SCH.',
        'JIBU PRI. SCH. GALADIMA KABAWA',
        'IGBOGODO PRI. SCH.',
        'JIBU, JIBU PRIMARY SCHOOL',
        'NEAR KOFAR SARKIN NOMA BYE KAHKI',
        'LOCAL GOVT. DISPENSARY JIBU',
        'MARARRABAN NWOKYON',
        'NAYI NAWA, NAYI NAWA PRIMARY SCHOOL',
        'NWOKYON PRI. SCH.',
        'NWOHWA, NWOHWA',
        'TAPARE, TAPARE PRIMARY SCHOOL',
        'TUDUN WADA PRI. SCH.',
        'TSE YONGUR PRI. SCH.',
        "VA'AYEM PRI. SCH.",
        'ZARIYA, ZARIYA',
        'ZONDOKU PRI. SCH.',
    ],
    'KENTE': [
        'AGAKU PRI. SCH.',
        'L.G. DISPENSARY AWUDU INGYU',
        'CHINKAI PRIMARY SCHOOL',
        'G.D.S.S. KENTE EMMANUEL EKERE',
        'G.D.S.S. KENTE',
        'GIDAN YAKU PRI. SCH.',
        'KENTE PRIMARY SCHOOL I',
        'KENTE PRIMARY SCHOOL II',
        'NEAR KOFAR ISHAKU',
        'KENTE PRI. SCH. KOFAR SAM ABE',
        'NEAR KOFAR KUNDU, CHINKAI',
        'NEAR KOFAR ISHAKU/UTUKU, SONDI',
        'CHINKAI PRI. SCH. KOFAR SARKIN KASUWA',
        'NEAR NDUR, NDUUL UGEMA',
        "SE'AN PRI. SCH.",
        'SHARAGH PRI. SCH.',
        'SONDI PRIMARY SCHOOL I',
        'SONDI PRIMARY SCHOOL II',
        'WARAWA PRI. SCH.',
        'UNG. KABAWA, UNGUWAR KABAWA',
        'UNG. S/CHINKAI, KOFAR SARKI',
    ],
    'PUJE': [
        'CENT. PRIMARY SCHOOL, CENTRAL PRIMARY SCHOOL',
        'PRI. SCH. GIDAN MOTO',
        'NEAR GEORGE TEN/HYUKU',
        'NEAR KOFAR HAKIMI SHISHI I',
        'CENTRAL PRI. SCH. HAKIMI SHISHI II',
        'HYUKU, HYUKU PRIMARY SCHOOL',
        'NEAR KOFAR USMAN FANYA',
        'NEAR KOFAR AJIDUKU',
        'CENTRAL PRI. SCH. KOFAR SHATIMA',
        'NEAR KOFAR INUWA BABA',
        'NIPOST KOFAR MOYI',
        'MAR. ISLAM PRIMARY SCHOOL I',
        'MAR. ISLAMIYA PRIMARY SCHOOL II',
        'MECHANIC VILLAGE, MECHANIC VILLAGE',
        "NEAR AKU UKA'S PALACE",
        'WUKARI EAST PRIMARY SCHOOL',
        'YAM MARKET, YAM MARKET',
    ],
    'RAFIN KADA': [
        'ABAKO/MBASHAGBA, MBASHAGBA',
        'PRI. SCH. R. KADA KOFAR VYON',
        'AKAWU YALGAM PRI. SCH.',
        'NEAR ALH. A.B. GAYA',
        'NEAR GAVYOSA',
        'NEAR JOHN NFORGWE',
        'NEAR KOFAR AWUDU AGBU',
        'NEAR KOFAR SARKIN R. KADA',
        'G.D.S.S. R. KADA',
        'NEAR KOFAR VYON R. KADA',
        'KUDU GAYA, KUDU GAYA',
        'MBASHAGBA U., MBASHAGBA UKANDE PRIMARY SCHOOL',
        'R/KADA PRIMARY SCHOOL',
        'TOR IWAMBE, TOR IWAMBE',
        'TOR IORSHAGA PRI. SCH.',
        'NEAR TSOKWA AGYOK',
        'YAWE GBEREVE, YAWE GBEREVE',
        'YUSUF YELLOW/ASON PRIMARY SCHOOL',
    ],
    'TSOKUNDI': [
        'AJUJI PRI. SCH.',
        'AYOTA PRI. SCH.',
        'AVI PRIMARY SCHOOL',
        'TSUKUNDI PRI. SCH. BABA TELA',
        "DA'A, DA'A PRIMARY SCHOOL",
        'GANI KODI, GANI KODI',
        'GIDAN IDI, GIDAN IDI PRIMARY SCHOOL',
        'G/HAKIMI G/IDI',
        'NEAR GIDAN MUHD. MAI KIFI',
        'IKYER NUM, IKYERNUM PRIMARY SCHOOL',
        'NEAR KOFAR AJIDUKU TURU',
        'PRI. SCH. MBAKUR-PUR',
        "PRI. SCH. SA'ANI",
        'NEAR KOFAR BAWA',
        'G.D.S.S. TSUKUNDI',
        'TSUKUNDI PRI. SCH.',
        'ZEGETE PRI. SCH.',
    ],
}

total_created = 0

for ward_name, pus in data.items():
    ward = Ward.objects.get(name=ward_name, lga=lga)
    for i, pu_name in enumerate(pus, start=1):
        pu, created = PollingUnit.objects.get_or_create(
            name=pu_name,
            ward=ward,
            defaults={'code': str(i).zfill(3)}
        )
        if created:
            total_created += 1
            print(f'  Created: [{ward_name}] {pu_name}')
        else:
            print(f'  Exists:  [{ward_name}] {pu_name}')

print(f'\nDone. {total_created} polling units created for WUKARI.')
