import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from election.models import LocalGovernmentArea, Ward, PollingUnit

lga = LocalGovernmentArea.objects.get(name='Jalingo')

data = {
    'ABBARE YELWA': [
        'ABBARE, ABBARE PRIMARY SCHOOL',
        'JAURO HOUSE OPEN SPACE',
        'JAURO SHAFO OPEN SPACE',
        'NEAR JAURO\'S HOUSE',
        'OPEN SPACE KOFAN JAURO',
        'POLICE STATION',
    ],
    'BARADE': [
        'OPEN SPACE, ZAIN MASK',
        'GDSS. SCHOOL GARIN MAGAMI',
        'AGADA\'ATA OPEN SPACE',
        'BEHIND MARKET SQUARE KOFAN BASHIR',
        'BENUE STREET OPEN SPACE',
        'OPP. HASSAN BAPPA COMPLEX OPEN SPACE',
        'CITY CLINIC OPEN SPACE KOFAR JIKA MURI',
        'OPP. SAURARA MOSQUE I',
        'OPP. SAURARA MOSQUE II',
        'BEHIND MKT. SQUARE KOFAR MALAM IDI',
        'OLD CITY CLINIC',
        'MARKET SQUARE KOFAR SABON SARKI',
        'BEHIND A.A. KASSA ROAD OPEN SPACE',
        'BEHIND MKT. SQUARE KOFARN WAKILI TASHA',
        'BEHIND UMCN',
        'MAGAMI PRIMARY SCHOOL',
        'MOHAMMED TUKUR PRIMARY SCHOOL I',
        'MOHAMMED TUKUR PRIMARY SCHOOL II',
        'MOHAMMED TUKUR PRIMARY SCHOOL III',
        'CITY CLINIC OPEN SPACE UNGUWAN USMAN',
    ],
    'KACHALLA SEMBE': [
        'FTC PERMANENT SITE NEAR W/SMEBE RD.',
        'BOREHOLE OPEN SPACE',
        'MARKET SQUARE KAUSWAN RUMFA',
        'JAURO PALACE OPEN SPACE KORKAYEL',
        'JAURO PALACE OPEN SPACE KOFAR MALAM GABDO',
        'BEHIND SALEJO HOUSE OPEN SPACE',
        'PRIMARY BOARD, PRIMARY BOARD',
        'SABON GARI PRIMARY SCHOOL',
        'ALONG GATE 1 ROAD OPEN SPACE',
        'WURO SEMBE, WURO SEMBE PRIMARY SCHOOL',
    ],
    'KONA': [
        'JAURO PALACE OPEN SPACE ANGUWAN GULUM',
        'NEW ERA P/NUR. SCH. OPEN SPACE',
        'EMIR PALACE OPEN SPACE I',
        'EMIR PALACE OPEN SPACE II',
        'FGGC, JALINGO',
        'HOWAI PRIMARY SCHOOL I',
        'HOWAI PRIMARY SCHOOL II',
        'NEAR JAURO\'S PALACE OPEN SPACE',
        'JAURO\'S PALACE OPEN SPACE JANBAMBU',
        'JAURO\'S PALACE OPEN SPACE JAURO TIPPI',
        'JAURO\'S PALACE OPEN SPACE JEKONO HOU',
        'ALONG KONA ROAD OPEN SPACE LAKAGANA',
        'ALONG KONA ROAD OPEN SPACE MINDA LAVOZING',
        'ALONG KONA ROAD OPEN SPACE MURKUNI',
        'ALONG KONA ROAD OPEN SPACE MURTAI',
        'NUKKAI PRIMARY SCHOOL I',
        'NUKKAI PRIMARY SCHOOL II',
        'TECHNOBAT OPEN SPACE',
        'BEHIND TIMBER MRKT OPEN SPACE',
        'STATE SECRETARIAT, JALINGO I',
        'STATE SECRETARIAT, JALINGO II',
    ],
    'MAJIDADI': [
        'W/HEAD HOUSE OPEN SPACE',
        'MAFINDI PRIM. SCHOOL ALHASSAN SAURARA',
        'MAFINDI PRI. SCHOOL GAJERE KUNZANG',
        'WATER BOARD OFFICE',
        'EMIR\'S PALACE OPEN SPACE',
        'ALONG EMIR\'S PALACE OPEN SPACE',
        'BEHIND CENTRAL MARKET',
        'ALONG KAROFI BRIDGE OPEN SPACE',
        'BOBBOJI BRIDGE OPEN SPACE',
        'MAFINDI PRIMARY SCHOOL I',
        'MAFINDI PRIMARY SCHOOL II',
        'MAFINDI PRIMARY SCHOOL III',
        'NURUL ISLAM OPEN SPACE',
        'TUDUN WADA CLINIC',
    ],
    'MAYO GOI': [
        'KOFAN MAIANGUWA OPEN SPACE ALI DANKUM I',
        'UNIVERSAL BASIC EDUCATION BOARD ALI DANKUM II',
        'JAURO PALACE OPEN SPACE ANGUWAN SHANU',
        'MODEL PRIMARY SCHOOL',
        'MINI MARKET I GINDIN DORUWA',
        'MINI MARKET II GINDIN DORUWA',
        'NITEL OPEN SPACE',
        'GOVT. COLLEGE, JALINGO',
        'HASSAN PRIMARY SCHOOL I',
        'HASSAN PRIMARY SCHOOL II',
        'HASSAN PRIMARY SCHOOL III',
        'JAKANDA ROAD OPEN SPACE JAURO MASHI I',
        'JAKANDA ROAD OPEN SPACE JAURO MASHI II',
        'FEDERAL MEDICAL CENTRE, JALINGO',
        'SPECIALIST HOSPITAL, JALINGO',
    ],
    'SARKIN DAWAKI': [
        'ALONG KAROFI ROAD OPEN SPACE BLIND WORKSHOP',
        'ALONG PALACE WAY OPEN SPACE',
        'BLIND WORKSHOP OPEN SPACE',
        'GALADIMA PLACE OPEN SPACE',
        'UBA MAIRIGA PALACE OPEN SPACE',
        'ALH. IBI HOUSE OPEN SPACE',
        'LAMORDE PRIMARY SCHOOL I',
        'LAMORDE PRIMARY SCHOOL II',
    ],
    'SINTALI': [
        'BEHIND AUK SHOPPING COMPLEX',
        'FORMER GATE WAY CLINIC OPEN SPACE',
        'OPP. CENTRAL MARKET OPEN SPACE',
        'KOFAN SINTALI, NEAR POLICE DIVISION',
        'FIRST BANK OPEN SPACE',
        'BEHIND BAPTIST CHURCH OPEN SPACE',
    ],
    "TURAKI 'A'": [
        'IMMIGRATION OFFICE I',
        'IMMIGRATION OFFICE II',
        'IMMIGRATION OFFICE III',
        'BEHIND MTD OPEN SPACE GINDIN RIMI',
        'OPP. UMMA CLINIC OPEN SPACE',
        'BEHIND MTD OPEN SPACE KOFAN ALHAJI GARKE',
        'DANBURAM PALACE OPEN SPACE KOFAN GAJAWA I',
        'KAIRAT CLINIC OPEN SPACE KOFAN GAJAWA II',
        'BEHIND HIGH COURT OPEN SPACE',
        'PRISON YARD OPEN SPACE',
        'MOHAMMED NYA PRIMARY SCHOOL I',
        'MOHAMMED NYA PRIMARY SCHOOL II',
        'MOHAMMED NYA PRIMARY SCHOOL III',
        'MOHAMMED NYA PRIMARY SCHOOL IV',
        'MOHAMMED NYA PRIMARY SCHOOL V',
        'MOHAMMED NYA PRIMARY SCHOOL VI',
    ],
    "TURAKI 'B'": [
        'BEHIND SSS OFFICE OPEN SPACE',
        'CENTRAL PRIMARY SCHOOL I',
        'CENTRAL PRIMARY SCHOOL II',
        'CENTRAL PRIMARY SCHOOL III',
        'JALINGO LOCAL GOVT. SECRETARIAT I',
        'JALINGO LOCAL GOVT. SECRETARIAT II',
        'GRA QUARTRS. OPEN SPACE',
        'JAURO PALACE OPEN SPACE SABON GARI',
    ],
}

total_created = 0

for ward_name, pus in data.items():
    ward = Ward.objects.get(name=ward_name, lga=lga)
    for i, pu_name in enumerate(pus, start=1):
        pu, created = PollingUnit.objects.get_or_create(
            name=pu_name,
            ward=ward,
            defaults={'code': str(i).zfill(3)}
        )
        if created:
            total_created += 1
            print(f'  Created: [{ward_name}] {pu_name}')
        else:
            print(f'  Exists:  [{ward_name}] {pu_name}')

print(f'\nDone. {total_created} polling units created for JALINGO.')
