import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from election.models import LocalGovernmentArea, Ward, PollingUnit

lga = LocalGovernmentArea.objects.get(name='GASSOL')

data = {
    'GASSOL': [
        'NOMADIC PRI. SCH, GARI SHUAIBU',
        'HAMMARUWA PRI. SCH. GASSOL',
        'ANG. BADIJA, BADIJA I',
        'MOHAMMED BOSE PRI. SCH. GASSOL',
        'NOMADIC PRI. SCH. GARIN SHUAIBU',
        'GASSOL, GASSOL',
        'GASSOL MAIN MARKET',
        'KANTI, KANTI',
        'DISPENSARY, KARAL',
        'KIR OPEN SPACE',
        'KWATAN TARU, K/TARU',
        'SOKKO TAWA, SOKKO TAWA',
        'TORO JANGA, TORO JANGA',
        'HAMMARUWA PRI. SCH. GASSOL II',
        'BADIJA DISPENSARY, BADIJA',
        'UPPER BENUE, UPPER BENUE',
        'WURO KESUM OPEN SPACE',
    ],
    'GUNDUMA': [
        'ABUJA OPEN SPACE',
        'BABA ALSO OPEN SPACE',
        'BARJANGA PRI. SCH.',
        'CHUL I, SABON DALE',
        'CHUL II, CHUL II',
        'DORON WURKUM OPEN SPACE',
        'PRI. SCH. GARI ATIKU',
        'GARIN BAPPA OPEN SPACE',
        'MOTOR PARK, GARIN BATURE',
        'PRI. SCH. GARIN GIDADO',
        'PRI. SCH, GARIN KIYARI',
        'MOTOR PARK, GARIN YELWA',
        'GORONDO OPEN SPACE',
        'GUNDUMA, KASUWAN GUNDUMA',
        'PRI. SCH, GUROWA',
        'MOTOR PARK, HAMMARI',
        'KAWO GILO OPN SPACE',
        'DISPENSARY, KUKA',
        'LARISKI OPEN SPACE',
        'PRI. SCH. GUNDUMA',
        'MOTOR PARK, GARIN MAGAJI',
        'MAGAJI II OPEN SPACE',
        'MAKAMA OPEN SPACE',
        'DISPENSARY, MAKURNA',
        'PRI. SCH. NABAYI',
        'NAWAKALA OPEN SPACE',
        'SANDARU OPEN SPACE',
        'PRI. SCH. WANKA',
        'PRI. SCH. YAYANI I',
        'PRI. SCH. YAYANI II',
    ],
    'MUTUM BIYU I': [
        'PRIMARY SCHOOL ACHI ARAGE',
        'DALHATU I, CENTRAL PRIMARY SCHOOL',
        'DALHATU II, CENTRAL PRIMARY SCHOOL',
        'DALHATU III, CENTRAL PRIMARY SCHOOL',
        'LOCAL GOVT. SECRETARIAT',
        'NURU ULUM PRI. SCH. I',
        'NURU ULUM PRI. SCH. II',
        'K/NANIDO PRI. SCH.',
        'SHANU I, CENTRAL PRIMARY SCHOOL',
        'SHANU II, CENTRAL PRIMARY SCHOOL',
        'NEPA OFFICE',
        'MAIN MARKET TIKE',
    ],
    'MUTUM BIYU II': [
        'COTTEGE HOSPITAL I',
        'COTTEGE HOSPITAL II',
        'BOREHOLE MUTUM BIYU',
        'M/BIYU MAIN MARKET',
        'KOFAR YAYA MANU',
        'KACHALLA PRI. SCH.',
        'ALMAJIRI PRI. SCH.',
        'JIBRIL I OPEN SPACE',
        'PRISON OFFICE',
        'LAWAN, KOFAN SARKI',
        'BAKIN KASUWA BULU',
        'BAKIN KASUWA I',
        'BAKIN KASUWA II',
    ],
    'NAM NAI': [
        'AUTA, G/AUTA',
        'BADA KOSHI I, BADA KOSHI I',
        'BADA KOSHI II, BADA KOSHI II',
        'BAYEL OPEN SPACE',
        'BUNGEL, G/BUNGEL',
        'DINAWOL OPEN SPACE',
        'GALADIMA OPEN SPACE',
        'GARIN ALI, GARIN ALI',
        'GARIN ABBA I, G/ABBA I',
        'GARIN ABBA II, G/ABBA II',
        'GARIN MALAM ABBA II, MALLAM ABBA II',
        'GARIN MUAZU OPEN SPACE',
        'JAURO BAPPA, JAURO BAPPA',
        'KOPPI, KOPPI',
        'BUBA LIMAN PRI. SCH.',
        'K/MAIGEMU PRI. SCH.',
        'KAWARI DISPENSARY',
        'KWATAN M. PRI. SCH.',
        'NAMNAI I, PRI. SCH.',
        'NAMNAI II CENTRAL PRY. SCHOOL',
        'NDAYARO PRI. SCH.',
        'SABON GIDA I OPEN SPACE',
        'SABON GIDA II OPEN SPACE',
        'TAKUM LABARAN OPEN SPACE',
        'TSIN TSIYA, TSIN TSIYA',
        'TURA TURAKEKE, T. TURAKEKE',
        'TIM-TIM PRI. SCH.',
        'NARAJE PRI. SCH.',
        'UNG. U. SIDDI OPEN SPACE',
        'UGN. YAKUBU DISPENSARY',
    ],
    'SABON GIDA': [
        'DINYA PRI. SCH.',
        'AYAM FELA OPEN SPACE',
        'G.D.S.S S/GIDA BOLAWA',
        'DAN ANACHA I, DAN ANACHA I',
        'DAN ANACHA II, DAN ANACHA II',
        'DAN ANACHA III, DAN ANACHA III',
        'DAN ANACHA IV, DAN ANACHA IV',
        'DINYA KUMATU, DINYA KUMATU',
        'DINYA NKETE, DINYA NKETE',
        'GINDIN DUTSE, DAN LADI HARUNA',
        'CENTRAL PRI. SCH. JIDDERE',
        'JOHN HIGH LEVEL, IORWUSE',
        'JOKIYA I OPEN SPACE',
        'JOKIYA II OPEN SPACE',
        'JOKIYA III OPEN SPACE',
        'G.D.S.S S/GIDA MAISAKA',
        'M.D.G HOSPITAL NANGURU I',
        'NANGURU II OPEN SPACE',
        'NONGO/ISHO PRIMARY SCHOOL',
        'S/GIDA II PRI. SCH.',
        'SCHOOL AREA DINYA',
        'SHIBI, S/GIDA PRIMARY SCHOOL',
        'TAKAI PRI. SCH.',
        'TURE-TURE I OPEN SPACE',
        'TURE-TURE II OPEN SPACE',
        'TURE-TURE III OPEN SPACE',
        'WANZAM I OPEN SPACE',
        'WANZAM II OPEN SPACE',
        'YAM MARKET I OPEN SPACE',
        'YAM MARKET II OPEN SPACE',
        'G/CHOLONGO OPEN SPACE',
        'YELWA I, YELWA I',
        'YELWA II, YELWA II',
        'YELWA III, YELWA III',
        'YELWA IV, YELWA IV',
        'YELWA DINYA I',
        'YELWA DINYA II',
    ],
    'SARKIN SHIRA': [
        'BAKIN KASUWA, BAKIN KASUWA',
        'DAN BAKI, UNG. DAN BAKI',
        'GARIN ABDULLAHI OPEN SPACE',
        'GARIN ALMAJIRI, GARIN ALMAJIRI',
        'GARIN JIBIR, UNGUWA DANBAKI',
        'GARIN KABO OPEN SPACE',
        'IBRAHIM YANDANG OPEN SPACE',
        'DISPENSARY, JAURO BARDE',
        'JAURO BELLO, JAURO BELLO',
        'JAURO HARUNA, JAURO HARUNA',
        'DISPENSARY, JAURO MANU I',
        'DISPENSARY, JAURO MANU II',
        'JAURO TAPE OPEN SPACE',
        'DISPENSARY, LALLAMI',
        'KOFAR DEBO OPEN SPACE',
        'LOMODU OPEN SPACE',
        'NYAMATA OPEN SPACE',
        'SABON GIDA OPEN SPACE',
        'SAMARI ADAM OPEN SPACE',
        'U/AJI, UNG. U. AJI',
        'MAIN MARKET, U/UFESHIGO',
        'WURO ABBA OPEN SPACE',
    ],
    'SENDIRDE': [
        'BAKIN KASUWA, DOMAYO BABBA',
        'DUTSE NUM OPEN SPACE',
        'GOTORU OPEN SPACE',
        'GUNGUN BODEL PRI. SCH.',
        'KOFAR J. DOMAYO PRI. SCH.',
        'MADAKI OPEN SPACE',
        'NDIYAWO PRI. SCH.',
        'NGOSAM I OPEN SPACE',
        'DISPENSARY NGOSAM II',
        'SENDIRDE MAIN MARKET',
        'SENDIRDE II, UNG. AHMADU I',
        'SENDIRDE III, UNG. AHMADU II',
        'WURO BOKKI DISPENSARY',
        'WURBO DISPENSARY',
        'DISPENSARY SENDIRDE',
    ],
    'TUTARE': [
        'TUTARE PRI. SCH. BAHAGO',
        'GARIN ALI OPEN SPACE',
        'PRI. SCH. GARIN BELLO',
        'GARIN DARE OPEN SPACE',
        'PRI. SCH, GARIN SULE',
        'MDG MATERNITY, MANJI',
        'MANJI II, ANG. KACHALLA',
        'PRI. SCH. MANJI',
        'PRI. SCH. SHEKA',
        'PRI. SCH, BAKIN TUDU',
        'PRI. SCH. TAKA FULANI',
        'PRI. SCH. TAKA JAURO',
        'MOTOR PARK, TAKA',
        'MOTOR PARK, GARIN TUKURA',
        'MDG MATERNITY, TAKA',
        'TAKA PRI. SCH, TAKA',
        'MDG MATERNITY, TUTARE',
        'G.D.S.S, TUTARE',
    ],
    'WUROJAM': [
        'DISPENSARY, WURO JAM',
        'PRI. SCH. AGURAGA I',
        'PRI. SCH. AGURAGA II',
        'DISPENSARY SANSANI',
        'PRI. SCH. WURO JAM',
        'PRI. SCH. GINDIN KOGI',
        'PRI. SCH. GWIWAN KOGI',
        'DISPENSARY, GWIWAN KOGI',
        'MATERNITY, GWIWAN KOGI I',
        'KUFAI PRI. SCH.',
        'MOTOR PARK, WURO JAM',
        'G.D.S.S WURO JAM',
        'G.D.S.S SANSANI',
        'SARKIN YAKI PRI. SCH.',
        'SANSANI MATERNITY CLINIC I',
        'SANSANI MATERNITY CLINIC II',
        'MOTOR PARK, SANSANI',
        'MIYETTI ALLAH PRI. SCH. WUROJAM',
        'MOTOR PARK, WURO JAM II',
    ],
    'WURYO': [
        'DISSOL PRI. SCH.',
        'DOBELI I PRI. SCH.',
        'DOBELI II PRI. SCH.',
        'DUNDEWA OPEN SPACE',
        'YAKUBU BABA PRI. SCH. I',
        'YAKUBU BABA PRI. SCH. II',
        'KOFAR BANA I OPEN SPACE',
        'KOFAR BANA II OPEN SPACE',
        'CATTLE MARKET NJIDDAWO I',
        'CATTLE MARKET NJIDDAWO II',
        'NJIDDAWO PRI.SCH.I',
        'NJIDDAWO PRI.SCH. II',
        'NOMADIC PRI. SCH. WURYO',
        'SUMAYE OPEN SPACE',
        'TELLA PRI. SCH.',
        'TELLA II PRI. SCH.',
        'TELLA III, TELLA PRIMARY SCHOOL',
        'TELLA IV, NJIDDAWO PRIMARY SCHOOL',
        'TELLA PRI. SCH. V',
        'WURYO PRI. SCH. I',
        'WURYO PRI. SCH. II',
        'WURYO MATERNITY MDG I',
        'WURYO MATERNITY MDG II',
        'WURYO MATERNITY MDG III',
        'WURYO PRI. SCH. IV',
        'WURYO PRI. SCH. V',
        'WURYO PRI. SCH. VI',
    ],
    'YARIMA': [
        'ANEMA PRI. SCH.',
        'BEMBAL, DISPENSARY',
        'DANBAZAU DISPENSARY',
        'GAGARA PRI. SCH.',
        'GARKO OPEN SPACE',
        'GARIN KARFE OPEN SPACE',
        'GILDI OPEN SPACE',
        'BABA ALSO PRI. SCH. GONORI',
        'GONORI MAIN MARKET',
        'MUMMUYE YERIMA, UNG. MUMUYAWA',
        'MATERNITY CLINIC YERIMA',
        'PRI. SCH. YOLA KAREJI',
        'BABA ALSO PRI. SCH. SARKIN NOMA',
        'BEMBAL PRI. SCH.',
        'YAYA DUDU OPEN SPACE',
        'YERIMA MAIN MARKET',
        'YUNKUM OPEN SPACE',
    ],
}

total_created = 0

for ward_name, pus in data.items():
    ward = Ward.objects.get(name=ward_name, lga=lga)
    for i, pu_name in enumerate(pus, start=1):
        pu, created = PollingUnit.objects.get_or_create(
            name=pu_name,
            ward=ward,
            defaults={'code': str(i).zfill(3)}
        )
        if created:
            total_created += 1
            print(f'  Created: [{ward_name}] {pu_name}')
        else:
            print(f'  Exists:  [{ward_name}] {pu_name}')

print(f'\nDone. {total_created} polling units created for GASSOL.')
