import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from election.models import LocalGovernmentArea, Ward, PollingUnit

lga = LocalGovernmentArea.objects.get(name='KARIM LAMIDO')

data = {
    'AMAR': [
        'TATU PRI. SCH.',
        'BARIKI PRY SCH.',
        'BINARI SEC. SCH.',
        'ANG. DAHIRU PRY SCH.',
        'ANG. DAMARA PRY SCH.',
        'FOOT BALL FIELD I',
        'FOOT BALL FIELD II',
        'NAHUTA PRI. SCH.',
        'ANG. MAHMUDA PRY SCH.',
        'SAMBO PRI. SCH.',
        'ANG. SIDDOKO PRY SCH.',
        'VELANGO PRI. SCH.',
        'ANG. WAKILI PRI. SCH.',
    ],
    'ANDAMIN': [
        'ANG. BALARABE, ANG. BALARABE',
        'ANG. BARAYA, ANG. BARAYA',
        'ANG. BELLO KUNSHENU',
        'ANG. DAMKA/R.ZAFI',
        'ANG. G/NDELA',
        'ANG. JAURO WADATA',
        'ANG. JEB-JEB/Y.KURA',
        'ANG. KOMBODORO',
        'ANG. KUKA UBANDOMA I',
        'ANG. KUKA UBANDOMA II',
        'ANG. KWATAN JEN',
        'ANG. MAISAMARI I',
        'ANG. MAISAMARI II',
        'ANG. TAFIDA',
        'ANG. TELAJUGU',
        'ANG. YABURO/DAMARE',
        'ANG. YERIMA GALADIMA',
        'ANG. ZANI/GWATI/UBANDOMA',
    ],
    'BACHAMA': [
        'ANGULE PRI. SCH.',
        'ANJODDO MATERNATY',
        'J. ALI PRI. SCH.',
        'J. BAYERO PRI. SCH.',
        'J. MANGA PRI. SCH.',
        'KAKKALA PRY SCH.',
        'MALAM SHEHU PRI. SCH.',
        'PARA DISPENSARY',
        'PAREJE PRI. SCH.',
        'SARKI MAIDOKI SEC. SCH.',
        'SENGE PRI. SCH.',
        'TURBAN YAKUBU PRI. SCH.',
        'WAKILI DISPENSARY',
    ],
    'BIKWIN': [
        'UNG ADAMU PRI. SCH.',
        'ARDIDO DAN PRI. SCH.',
        'BELLO ABBA PRI. SCH.',
        'DAURA PRI. SCH.',
        'GANGARA GOVT. DAY',
        'GALADIMA PRI. SCH.',
        'ISA YOHANNA GOVT',
        'ZOH MAKARAU PRI. SCH.',
        'ISKADARI DAY CARE SCH.',
        'KAMUEL FOOTBALL FIELD',
        'NANZO PRI. SCH.',
        'SARKIN LOH PRI. SCH.',
        'SARKIN PANYA PRI. SCH.',
        'WAWA DUTSE PRI. SCH.',
        'YAMDI SIMAN PRI. SCH.',
        'YUSUF DOGO PRI. SCH.',
    ],
    'DAROFAI': [
        'ATIKU PRI. SCH.',
        'BAKA NYALA PRI. SCH.',
        'UNG. BARAYA PRI. SCH.',
        'DON GORO DISPENSARY',
        'GALADIMA/KARIM PRI. SCH.',
        'GWALAK PRI. SCH.',
        'LOBA PRI. SCH.',
        'BANYAM PRI. SCH. I',
        'BANYAM PRI. SCH. II',
        'GENERAL HOPITAL',
        'MINGEH PRI. SCH.',
        'FOOTBALL FIELD SALLAH/IBRAHIM',
        'SAMBO PRI. SCH.',
        'BAMBUR PRI. SCH. I',
        'BAMBUR PRI. SCH. II',
        'MAMMAN PRI. SCH.',
        'FOOTBALL FIELD T. SALLAH',
        'DISPENSARY Y.T. USMAN',
    ],
    'DIDANGO': [
        'BADAKOSHI PRI. SCH.',
        'BALASA PRI. SCH.',
        'BAKOREGE DISPENSARY',
        'JUKUN PRI. SCH.',
        'GAJERE PRI. SCH.',
        'HABU GARO PRI. SCH.',
        'HAUSAWA PRI. SCH. I',
        'HAUSAWA PRI. SCH. II',
        'IBRAHIM .J. PRI. SCH.',
        'ISHAKU PRI. SCH.',
        'LARO DISPENSARY',
        'NASARAWA PRI. SCH.',
        'SHOMON NBAI PRI. SCH.',
        'S. JUKUN PRI. SCH.',
        'WAMBAI PRI. SCH.',
    ],
    'JEN ARDIDO': [
        'ADI HAMMAN NWADAH PRI. SCH.',
        'DOGO PRI. SCH.',
        'ARDO TASHI PRI. SCH.',
        'NANAH PRI. SCH. I',
        'NAHAH PRI. SCH. II',
        'DOYI SALI PRI. SCH.',
        'FITOWA PRI. SCH.',
        'GWAMINA PRI. SCH.',
        'HAUSAWA CENT PRI. SCH.',
        'JIMAN CENTRAL PRI. SCH.',
        'JAKKA PRI. SCH.',
        'MUSA SHEHU PRI. SCH.',
        'SARKIN JEN PRI. SCH.',
    ],
    'JEN KAIGAMA': [
        'JEN PRI. SCH.',
        'SABON GARI PRI. SCH.',
        'SAREDOU PRI. SCH. I',
        'SAREDOU PRI. SCH. II',
        'KUSSAKU PRI. SCH.',
        'J/NWAMIN LIDDA PRI. SCH.',
        'BAMBUKA GOVT. DAY',
        'JAKKA PRI. SCH. SAREDOU',
        'DADIYA PRI. SCH.',
        'ZAPTE PRI. SCH. I',
        'JEN. PRI. SCH. I',
        'JEN. PRI. SCH. II',
        'ZAPTE PRI. SCH. II',
        'DADIYA PRI. SCH. ZAKI',
        'ZANG. BAMBUKA PRI. SCH.',
        'ZANYA PRI. SCH.',
    ],
    'KARIM "A"': [
        'UNG. AHMADU I',
        'UNG. AHMADU II',
        'UNG. AJIYA',
        'ANG. AJIYA USMANU',
        'UNG. AMINU',
        'UNG. DARE',
        'UNG. GAGARE',
        'UNG. GALADIMA',
        'UNG. GARBA',
        'UNG. KACHALA',
        'UNG. LAWAN BUKI',
        'UNG. MAIKASADA',
        'SARKIN YAMMA',
        'UNG. YIDI',
    ],
    'KARIM "B"': [
        'UNG. BARDE HAMIDU',
        'UNG. BUBA/ALI',
        'UNG. GWENZU/JACOB',
        'UNG. KAIGAMA',
        'UNG. KAIGAMA JATAU',
        'UNG. LIKITA BABA',
        'UNG. MANZO',
        'UNG. NIYE',
        'UNG. YAKUBU',
        'UNG. YAKUBU/MAMBILO',
        'UNG. YUSUFU CHIROMA',
    ],
    'KWANCHI': [
        'ANG. AUDU ALI',
        'ANG. BABA DOGO',
        'ANG. BURO',
        'ANG. CHIROMA',
        'ANG. DINYA/NAYI',
        'ANG. HAMZA',
        'ANG. MAIKANO',
        'ANG. PASSALI',
        'ANG. PIRIBI',
        'ANG. SABONGARI/SALLAH',
        'ANG. SAU DOGARI',
        'ANG. SHAMAKI',
        'ANG. UMARU/DUKULE',
    ],
}

total_created = 0

for ward_name, pus in data.items():
    ward = Ward.objects.get(name=ward_name, lga=lga)
    for i, pu_name in enumerate(pus, start=1):
        pu, created = PollingUnit.objects.get_or_create(
            name=pu_name,
            ward=ward,
            defaults={'code': str(i).zfill(3)}
        )
        if created:
            total_created += 1
            print(f'  Created: [{ward_name}] {pu_name}')
        else:
            print(f'  Exists:  [{ward_name}] {pu_name}')

print(f'\nDone. {total_created} polling units created for KARIM LAMIDO.')
